version: '3.3'

services:
  nginx:
    container_name: nginx
    build: ./build/nginx-1.15.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./docker/logs/nginx:/var/log/nginx
      - ./docker/config/nginx/conf.d:/etc/nginx/conf.d
    restart: always
    tty: true
    networks:
     - lnmp-networks
  php73:
    container_name: php73
    build: ./build/php73
    volumes:
      - ./www:/var/www/html
      - ./docker/logs/php:/var/log/php
    tty: true
    restart: always
    depends_on:
      - nginx
      - mysql
      - redis
    links:
      - mysql:mysql
      - redis:redis
    networks:
      - lnmp-networks
  mysql:
    container_name: mysql
    image: daocloud.io/library/mysql:5.7.7
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - lnmp-networks
  redis:
    container_name: redis
    image: daocloud.io/library/redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis:/data
    command: redis-server --appendonly yes
    networks:
      - lnmp-networks
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./docker/data/mongo:/data/db
    command: [ --auth ]
    networks:
      - lnmp-networks
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.12.0
    environment:
      - "cluster.name=elasticsearch"       # 设置集群名称为 es
      - "discovery.type=single-node"       # 以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"  # 设置使用jvm内存大小
    volumes:
      - ./docker/data/es:/usr/share/elasticsearch/data:rw     # 数据文件挂载
      - ./docker/plugins/es:/usr/share/elasticsearch/plugins  # 插件文件挂载
    ports:
      - 9200:9200
      - 9300:9300
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 1000M
        reservations:
          memory: 200M
    networks:
      - lnmp-networks
  kibana:
    image: kibana:7.12.0
    container_name: kibana
    depends_on:
      - elasticsearch
    volumes:
      - ./docker/config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    privileged: true    #环境变量
    networks:
      - lnmp-networks
networks:
 lnmp-networks:
