version: "3"
services:
  code_zookeeper:
    image: wurstmeister/zookeeper
    container_name: code_zookeeper
    environment:
      TZ: Asia/Shanghai
    ports:
      - "2181:2181"
    networks:
      - code_networks

  code_kafka:
    image: wurstmeister/kafka
    container_name: code_kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=code_zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - code_zookeeper
    networks:
      - code_networks

networks:
  code_networks:           # 网络
    driver: bridge    # 桥接模式
