version: '3.3'

services:
  lnmp-nginx:
    container_name: lnmp-nginx
    build: ./build/nginx-1.15.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./docker/config/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/logs/nginx:/var/log/nginx
    restart: always
    tty: true # 为容器分配一个伪终端，就相当于 docker run -t
    networks:
     - lnmp-networks
  lnmp-php73:
    container_name: lnmp-php73
    build: ./build/php73
    volumes:
      - ./www:/var/www/html
      - ./docker/logs/php:/var/log/php
    tty: true
    restart: always
    depends_on:
      - lnmp-nginx
      - lnmp-mysql
      - lnmp-redis
    links:
      - lnmp-mysql:mysql
      - lnmp-redis:redis
    networks:
      - lnmp-networks
  lnmp-mysql:
    container_name: lnmp-mysql
    image: daocloud.io/library/mysql:5.7.7
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - lnmp-networks
  lnmp-redis:
    container_name: lnmp-redis
    image: daocloud.io/library/redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis:/data
    command: redis-server --appendonly yes
    networks:
      - lnmp-networks
  lnmp-mongo:
    container_name: lnmp-mongo
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./docker/data/mongo:/data/db
    command: [ --auth ]
    networks:
      - lnmp-networks
networks:
 lnmp-networks:
   driver: bridge
