version: '3.3'

services:
  lnmp_nginx:
    container_name: lnmp_nginx
    build: ./build/nginx-1.15.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./docker/config/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/logs/nginx:/var/log/nginx
    restart: always
    tty: true # 为容器分配一个伪终端，就相当于 docker run -t
    networks:
     - lnmp_networks
  lnmp_php73:
    container_name: lnmp_php73
    build: ./build/php73
    volumes:
      - ./www:/var/www/html
      - ./docker/logs/php:/var/log/php
    tty: true
    restart: always
    depends_on:
      - lnmp_nginx
      - lnmp_mysql
      - lnmp_redis
      - lnmp_mongo
    links:
      - lnmp_mysql:mysql
      - lnmp_redis:redis
      - lnmp_mongo:mongo
    networks:
      - lnmp_networks
  lnmp_mysql:
    container_name: lnmp_mysql
    image: mysql/mysql-server:8.0.28
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    networks:
      - lnmp_networks
  lnmp_redis:
    container_name: lnmp_redis
    image: redis:6.2.5
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis:/data
    environment:
      TZ: Asia/Shanghai
    command: "redis-server --requirepass 123456  --appendonly yes"
    networks:
      - lnmp_networks
  lnmp_mongo:
    container_name: lnmp_mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ./docker/data/mongo:/data/db
    command: [ --auth ]
    networks:
      - lnmp_networks
networks:
 lnmp_networks:
   driver: bridge
